require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

inherit_from:
  - .rubocop_local.yml
  - .rubocop_todo.yml

AllCops:
  DisplayStyleGuide: true

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: should

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/ScatteredSetup:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

# Later? https://robots.thoughtbot.com/don-t-stub-the-system-under-test
RSpec/SubjectStub:
  Enabled: false
